export interface AreaData {
  slug: string;
  name: string;
  avgPrice: string;
  avgPriceNum: number;
  type: "borough" | "county";
  note: string;
  buyerProfile: string;
  localKnowledge: string;
  faqs: { q: string; a: string }[];
}

export const areas: AreaData[] = [
  {
    slug: "barking-and-dagenham",
    name: "Barking and Dagenham",
    avgPrice: "£350,000",
    avgPriceNum: 350000,
    type: "borough",
    note: "One of London's most affordable boroughs, popular with first-time buyers.",
    buyerProfile: "First-time buyers, young families, and investors seeking value in east London.",
    localKnowledge: "Barking and Dagenham sits on the Elizabeth line corridor, making commuting to central London straightforward. The regeneration around Barking Riverside is attracting first-time buyers who need a mortgage adviser who understands affordable housing schemes including Shared Ownership and First Homes.",
    faqs: [
      { q: "Can I get a mortgage in Barking and Dagenham with a 5% deposit?", a: "Yes. With average prices around £350,000, a 5% deposit of £17,500 is achievable for many buyers. As your mortgage adviser, we'll identify lenders offering competitive rates at 95% LTV and explore whether Shared Ownership or First Homes schemes could further reduce the deposit needed." },
      { q: "Is Barking and Dagenham good for buy to let investment?", a: "It can offer strong rental yields given lower purchase prices relative to central London. We advise on whether to buy in personal name or via a limited company based on your tax position, and which lenders assess rental income most favourably for this area." },
      { q: "What mortgage advice is available for new-build flats in Barking Riverside?", a: "New-builds come with specific considerations — some lenders apply caps on new-build flats, particularly above certain storeys. We work with lenders who are new-build friendly and ensure your Agreement in Principle is in place before you reserve." },
    ],
  },
  {
    slug: "barnet",
    name: "Barnet",
    avgPrice: "£600,000",
    avgPriceNum: 600000,
    type: "borough",
    note: "Popular with families; excellent schools and good transport links north of London.",
    buyerProfile: "Upsizing families, professionals commuting into central London, and Jewish community buyers.",
    localKnowledge: "Barnet's strong school catchments and proximity to the Northern and Thameslink lines make it one of north London's most sought-after boroughs. With average prices at £600,000, a detailed affordability assessment is essential — we help clients understand exactly how much lenders will offer based on income multiples and structure.",
    faqs: [
      { q: "How much can I borrow for a £600,000 property in Barnet?", a: "Most lenders offer 4–4.5x your gross household income. Some professional lenders offer up to 5.5x for high-earning applicants. As your adviser, we'll match you to the right lender for your income type, whether employed, self-employed, or a contractor." },
      { q: "My partner is a teacher and I'm a contractor — can we both get a mortgage?", a: "Absolutely. We regularly advise mixed-income households in Barnet. Teacher mortgages are straightforward; contractor income is assessed on day rate or accounts depending on your setup. We identify lenders who treat both income types favourably together." },
      { q: "Should I remortgage to fund a home extension in Barnet?", a: "A further advance or remortgage can release equity for extensions. With average Barnet property values, many homeowners have substantial equity. We'll compare further advance rates from your current lender against whole-of-market remortgage options." },
    ],
  },
  {
    slug: "bexley",
    name: "Bexley",
    avgPrice: "£390,000",
    avgPriceNum: 390000,
    type: "borough",
    note: "Leafy south-east London borough with strong transport links and community feel.",
    buyerProfile: "Families and commuters valuing space and relative affordability in south-east London.",
    localKnowledge: "Bexley offers more space for money than inner south-east London boroughs. With Elizabeth line access from Abbey Wood and good road links, it attracts buyers who want a house rather than a flat. Mortgage advice here often involves helping buyers understand how to structure affordability when moving from renting to ownership.",
    faqs: [
      { q: "What deposit do I need for a house in Bexley?", a: "A 10% deposit of around £39,000 opens up the most competitive rates. At 5% deposit (£19,500) you can still access mortgage deals, though fewer lenders compete at this LTV. We'll map out exactly which lenders offer the right deal for your deposit size." },
      { q: "Are there Help to Buy alternatives for buyers in Bexley?", a: "With Help to Buy closed nationally, Shared Ownership and the First Homes scheme (for eligible buyers) are the main routes to buying with a smaller deposit. We advise on eligibility and which lenders participate in each scheme." },
      { q: "Can I get mortgage advice if I have a previous missed payment?", a: "Yes. Adverse credit doesn't automatically mean you can't get a mortgage. We assess your full credit profile and match you to specialist lenders who consider your circumstances in full, rather than a simple credit score pass/fail." },
    ],
  },
  {
    slug: "brent",
    name: "Brent",
    avgPrice: "£530,000",
    avgPriceNum: 530000,
    type: "borough",
    note: "Diverse, well-connected borough with Wembley regeneration driving demand.",
    buyerProfile: "First-time buyers, investors, and families attracted by Jubilee and Bakerloo line access.",
    localKnowledge: "Brent is one of London's most diverse boroughs and has seen significant regeneration particularly around Wembley. Buyers here often have complex income structures — multiple jobs, agency work, or self-employment — and benefit from advice that interprets their income accurately to lenders.",
    faqs: [
      { q: "I work agency shifts in Brent — will lenders accept my income?", a: "Yes, but lender policies vary significantly. Some require 12 months of agency history; others accept 6 months. We identify which lenders take the most favourable view of variable or zero-hours income, and present your case compellingly." },
      { q: "Is Wembley a good area for buy to let investment?", a: "Wembley offers solid yields driven by strong rental demand from stadium events, transport links, and the international community. We advise on the right mortgage structure — personal versus limited company — and identify lenders whose rental income calculations work for this area." },
      { q: "What support is available for Islamic mortgage (Sharia-compliant) buyers in Brent?", a: "Sharia-compliant home purchase plans (HPPs) are available through a number of UK providers. We can discuss how these work and, where we have lender relationships, help you access appropriate products. We always clarify the full options available." },
    ],
  },
  {
    slug: "bromley",
    name: "Bromley",
    avgPrice: "£490,000",
    avgPriceNum: 490000,
    type: "borough",
    note: "Largest London borough by area — suburban feel with great schools.",
    buyerProfile: "Families relocating from inner London, upsizers, and professionals on the Thameslink corridor.",
    localKnowledge: "Bromley is one of the most suburban of London's boroughs, with many buyers coming from inner south-east London seeking more space. With average prices around £490,000, buyers here often need to maximise borrowing while keeping monthly payments manageable — something we address through careful rate and term structuring.",
    faqs: [
      { q: "Can I afford to upsize in Bromley from a flat in Lewisham?", a: "This is a common move we help with. Using the equity from your Lewisham flat as a deposit, and optimising borrowing on your new household income, we can often make the numbers work. We model different scenarios so you understand exactly what's achievable before you start viewing." },
      { q: "How does remortgaging work when I want to add my partner to the mortgage in Bromley?", a: "Adding a partner requires a full remortgage — the existing mortgage ends and a new joint one begins. We assess both incomes together, find the best whole-of-market rate, and manage the process including any stamp duty land tax considerations." },
      { q: "What is the mortgage process for buying a new-build in Bromley?", a: "New-builds typically require an exchange within 28 days of reservation, so getting your Agreement in Principle early is critical. We keep your AIP valid and manage the full application so you're ready to exchange when the developer requires." },
    ],
  },
  {
    slug: "camden",
    name: "Camden",
    avgPrice: "£850,000",
    avgPriceNum: 850000,
    type: "borough",
    note: "Prime inner north London borough with strong cultural identity and excellent transport.",
    buyerProfile: "High-earning professionals, overseas buyers, and upsizers targeting prime London property.",
    localKnowledge: "Camden's prime locations — Hampstead, Primrose Hill, Belsize Park — attract high-net-worth buyers where bespoke mortgage advice is essential. Loans above £500,000 often require specialist lenders with more nuanced underwriting, and we work with private banking contacts as well as mainstream lenders to find the right fit.",
    faqs: [
      { q: "How do I get a large mortgage in Camden at £850,000 or above?", a: "At this price point, high-street lenders become less suitable. Private banks and specialist lenders offer more flexibility on income multiples and asset-based lending. We assess your full financial picture and identify the lender whose criteria you best meet." },
      { q: "I'm an overseas buyer — can I get a mortgage for a Camden property?", a: "Yes, though fewer lenders participate. Eligibility typically depends on residency status, income source, and deposit size. We advise expat and non-UK-resident buyers regularly and can identify appropriate lenders for your specific situation." },
      { q: "Is it worth using an independent adviser rather than my private bank for a Camden mortgage?", a: "Your private bank can only offer their own products. An independent whole-of-market adviser has access to the full range, including other private banks and specialist lenders. We compare all options so you're confident you have the right mortgage, not just the most convenient one." },
    ],
  },
  {
    slug: "city-of-london",
    name: "City of London",
    avgPrice: "£750,000",
    avgPriceNum: 750000,
    type: "borough",
    note: "Small but iconic — high-rise residential above the financial district.",
    buyerProfile: "City workers, investors, and international buyers seeking pied-à-terre or rental investments.",
    localKnowledge: "The City of London's residential market is dominated by high-rise flats, many leasehold. Lenders apply specific criteria to high-rise residential and short-leasehold properties. We advise buyers on which lenders are comfortable with City of London apartments and what lease length requirements apply.",
    faqs: [
      { q: "Do lenders have concerns about high-rise flats in the City of London?", a: "Some lenders restrict lending on buildings above a certain height or percentage of flats in a block. Post-Grenfell, EWS1 certificates may be required. We identify lenders whose criteria match the specific building you're purchasing." },
      { q: "What lease length do I need on a City of London flat to get a mortgage?", a: "Most lenders require 85+ years remaining at the end of the mortgage term. We check this early in the process and, where the lease is shorter, advise on extending before or simultaneously with the purchase." },
      { q: "I want to buy a City of London flat as a pied-à-terre investment — how is this treated?", a: "Buy to let criteria apply if you intend to rent it out. If it will be a second home, standard residential criteria apply. The distinction matters for stamp duty (additional 3% for second properties) and lender choice. We advise on the most appropriate structure." },
    ],
  },
  {
    slug: "croydon",
    name: "Croydon",
    avgPrice: "£400,000",
    avgPriceNum: 400000,
    type: "borough",
    note: "South London's commercial hub, undergoing significant regeneration.",
    buyerProfile: "First-time buyers, buy-to-let investors, and commuters using fast trains to London Bridge and Victoria.",
    localKnowledge: "Croydon is one of south London's most accessible boroughs with fast trains to central London and good value for money. The regeneration of central Croydon has renewed interest from investors and first-time buyers. Mortgage advice in Croydon often involves navigating new-build schemes and affordable housing options alongside standard purchases.",
    faqs: [
      { q: "What government schemes are available for first-time buyers in Croydon?", a: "Shared Ownership developments are active in Croydon, allowing you to buy a share (typically 25-75%) and pay rent on the remainder. First Homes is also available on qualifying new-builds, offering a discount of at least 30% for eligible local buyers. We explain all options and which lenders participate." },
      { q: "Is Croydon good value for buy to let investment?", a: "Croydon offers a combination of relative affordability and strong rental demand from commuters and London workers. Yields can be attractive compared to inner-south London. We model rental income against mortgage costs and advise on personal name versus limited company ownership." },
      { q: "I have a Help to Buy equity loan — can I remortgage my Croydon property?", a: "Yes, but you must repay or retain the Help to Buy equity loan when you remortgage unless you're doing a like-for-like term and rate change with a participating lender. We clarify all the rules and model the best financial outcome for your situation." },
    ],
  },
  {
    slug: "ealing",
    name: "Ealing",
    avgPrice: "£550,000",
    avgPriceNum: 550000,
    type: "borough",
    note: "The Queen of the Suburbs — Elizabeth line transformed west London commuting.",
    buyerProfile: "Families, professionals, and Heathrow-area workers attracted by excellent schools and transport.",
    localKnowledge: "The Elizabeth line has been transformational for Ealing, cutting journey times to central London significantly. This has pushed property values up but also broadened buyer demand. Mortgage advice here often involves helping buyers understand affordability as values have risen, and identifying lenders comfortable with Ealing's competitive market.",
    faqs: [
      { q: "The Elizabeth line has pushed Ealing prices up — can I still afford to buy here?", a: "With average prices around £550,000, a household income of around £100-120k is typically needed for a standard mortgage. There are options for higher-income professionals, and we explore all avenues including joint borrower/sole proprietor arrangements for family help." },
      { q: "I'm buying in Ealing as a London professional with a bonus — how is bonus income assessed?", a: "Bonus income treatment varies widely. Some lenders take 100% of last year's bonus; others average over two years or exclude it. We identify which lenders will recognise your full income package most favourably." },
      { q: "What advice do you give for buying a flat above a shop in Ealing?", a: "Commercial-above property can restrict lender choice. We identify which lenders are comfortable with the property type and ensure your survey flags any issues. This is an area where whole-of-market advice is particularly valuable over going direct to one lender." },
    ],
  },
  {
    slug: "enfield",
    name: "Enfield",
    avgPrice: "£430,000",
    avgPriceNum: 430000,
    type: "borough",
    note: "North London border borough with green space and more affordable family homes.",
    buyerProfile: "Families escaping higher-priced inner north London, first-time buyers, and commuters.",
    localKnowledge: "Enfield sits at the northern edge of Greater London and offers more space for money than neighbouring Barnet. It has both urban and suburban neighbourhoods, and buyers here are often seeking a first family home. Mortgage advice here frequently involves helping clients understand how far their deposit goes and which areas of the borough represent best value.",
    faqs: [
      { q: "Is Enfield affordable for a first-time buyer household income of £60,000?", a: "At a combined income of £60,000, most lenders will offer £240,000-£270,000. With savings for a deposit, Enfield's lower price points make homeownership achievable. We model exactly what's possible and identify lenders offering the highest multiples for your income type." },
      { q: "What is the stamp duty for a first-time buyer purchasing a £430,000 home in Enfield?", a: "First-time buyers pay no stamp duty on the first £300,000 and 5% on the portion from £300,001 to £500,000. On £430,000 that means £6,500. We factor this into your overall budget planning as part of our initial advice." },
      { q: "Can I get a mortgage on a shared ownership property in Enfield?", a: "Yes. Shared Ownership mortgages are available through participating lenders. We advise on the shares available, the rent payable on the retained share, and what the total monthly outgoing will be — both mortgage and rent — so you have a clear picture before committing." },
    ],
  },
  {
    slug: "greenwich",
    name: "Greenwich",
    avgPrice: "£450,000",
    avgPriceNum: 450000,
    type: "borough",
    note: "Historic riverside borough with strong regeneration and Elizabeth line access.",
    buyerProfile: "Young professionals, first-time buyers, and upsizers drawn by riverside living and good transport.",
    localKnowledge: "Greenwich benefits from the Elizabeth line at Woolwich, Crossrail connectivity, and ongoing riverside regeneration. It attracts both first-time buyers and those upsizing from inner south-east London. Buyers here often face competition on property, making it important to have mortgage decisions in place before viewing.",
    faqs: [
      { q: "How quickly can I get an Agreement in Principle for a Greenwich property?", a: "We can typically secure an Agreement in Principle within 24 hours of receiving your documentation. This puts you in a strong position when making offers in a competitive market like Greenwich. We keep your AIP current throughout your search." },
      { q: "Are there many new-build options in Greenwich?", a: "Yes — Woolwich and the Royal Arsenal are active new-build areas. New-build mortgages have specific considerations around completion timelines and mortgage offer validity. We ensure your application is structured to meet developer exchange and completion requirements." },
      { q: "What is the mortgage advice for buyers using the Bank of Mum and Dad in Greenwich?", a: "Family gifted deposits are acceptable to most lenders but must be documented correctly — a letter confirming it's a gift not a loan. We handle the paperwork and ensure the lender is satisfied, making the process straightforward for all parties." },
    ],
  },
  {
    slug: "hackney",
    name: "Hackney",
    avgPrice: "£620,000",
    avgPriceNum: 620000,
    type: "borough",
    note: "Hip inner east London borough with strong creative community and premium prices.",
    buyerProfile: "High-earning professionals, creatives, and investors in one of east London's priciest boroughs.",
    localKnowledge: "Hackney's desirability has pushed prices to premium levels for east London. Areas like London Fields, Broadway Market, and Stoke Newington command high demand. At £620,000 average, buyers here need significant income or equity, and advice on maximising borrowing within responsible limits is a key part of our service.",
    faqs: [
      { q: "How do lenders treat freelance income for a Hackney buyer?", a: "Freelance income is assessed differently by each lender. Many look at two years' accounts or SA302s; some will consider projected income. We identify which lenders will give you the most credit for your freelance earnings and advise on whether the timing of your application matters." },
      { q: "What mortgage options exist for Hackney buyers with a high student loan balance?", a: "Student loan repayments are factored into affordability calculations. We identify lenders who apply the most favourable treatment of student loan repayments and advise on whether voluntary repayments make sense before applying." },
      { q: "I'm buying a Victorian conversion flat in Hackney — are there mortgage restrictions?", a: "Victorian conversions are generally mortgageable, though lenders look at the number of flats in the block, the lease length, and the building's overall structure. Studio flats and very small units can be more restrictive. We check property criteria early so there are no surprises." },
    ],
  },
  {
    slug: "hammersmith-and-fulham",
    name: "Hammersmith and Fulham",
    avgPrice: "£700,000",
    avgPriceNum: 700000,
    type: "borough",
    note: "Prime west London borough with riverside living and strong professional demand.",
    buyerProfile: "High-earning professionals, upsizing families, and media/finance workers in west London.",
    localKnowledge: "Hammersmith and Fulham is one of west London's most sought-after boroughs, blending riverside locations with excellent transport. At £700,000 average, buyers need substantial income, and many require advice on income structuring — particularly bonuses, carried interest, and complex pay packages common in finance and media.",
    faqs: [
      { q: "How is carried interest or deferred compensation treated by mortgage lenders?", a: "These complex income types vary significantly in how lenders treat them. Some specialist and private lenders will consider guaranteed bonus or vested equity. We work with clients in finance to present their full compensation package in the most effective way possible." },
      { q: "What are the options for a high-value interest-only mortgage in Hammersmith and Fulham?", a: "Interest-only is available for high-value buyers, typically requiring significant equity or assets. Lenders require a credible repayment strategy — sale of property, investments, or pension. We advise on whether interest-only is appropriate and which lenders offer it at this price point." },
      { q: "I want to buy in Fulham and rent out my current flat — what mortgage advice do I need?", a: "You'll need consent to let from your current lender or a remortgage to buy to let, plus a new residential mortgage for your Fulham purchase. We manage both simultaneously, ensuring consent to let is granted and your new mortgage is in place without a gap." },
    ],
  },
  {
    slug: "haringey",
    name: "Haringey",
    avgPrice: "£580,000",
    avgPriceNum: 580000,
    type: "borough",
    note: "Diverse north London borough stretching from Tottenham to Muswell Hill.",
    buyerProfile: "Young professionals, families, and buyers pricing out of Islington and Hackney.",
    localKnowledge: "Haringey spans a wide range of neighbourhoods — from up-and-coming Tottenham to the premium Muswell Hill and Crouch End. Buyers often find they can afford more here than in neighbouring boroughs. Mortgage advice in Haringey frequently involves helping buyers understand which areas offer best value relative to their budget.",
    faqs: [
      { q: "Is Tottenham a good area to buy for value in Haringey?", a: "Tottenham has seen significant regeneration around the Spurs stadium and improved transport links. It represents one of north London's better-value entry points. We advise buyers on the mortgage options available and, for investors, on rental yield potential relative to purchase costs." },
      { q: "Can I get mortgage advice if I'm a teacher buying alone in Haringey?", a: "Yes. As a single buyer in Haringey, the key is maximising your borrowing potential. Some lenders offer enhanced income multiples for certain professions. We identify the right lender for your income and career stage." },
      { q: "What's the remortgage process for a Haringey homeowner looking to release equity?", a: "Equity release through remortgage involves assessing your current equity, the cost of your existing deal, and whole-of-market rates. We compare your current lender's retention offers against the full market and advise whether switching makes financial sense." },
    ],
  },
  {
    slug: "harrow",
    name: "Harrow",
    avgPrice: "£500,000",
    avgPriceNum: 500000,
    type: "borough",
    note: "North-west London borough with excellent schools and Metropolitan line access.",
    buyerProfile: "Families, South Asian community buyers, and professionals on the Metropolitan and Chiltern lines.",
    localKnowledge: "Harrow on the Hill and Pinner are particularly sought-after within the borough, driven by excellent schools and leafy environments. The area has a large South Asian community and a high proportion of family homes. Mortgage advice here often involves multigenerational living arrangements and joint family purchases.",
    faqs: [
      { q: "Can multiple family members jointly apply for a mortgage in Harrow?", a: "Yes — joint mortgages with up to four applicants are available. We advise on how each applicant's income and credit history affects the application, and structure the application to maximise combined borrowing power." },
      { q: "I want to buy a larger family home in Harrow with help from my parents — what are the options?", a: "Options include a joint borrower/sole proprietor arrangement (parents on the mortgage but not the title), a family gifted deposit, or a guarantor mortgage. Each has different tax and liability implications. We explain all options clearly so your family can make an informed choice." },
      { q: "Are Harrow property prices likely to hold for remortgaging purposes?", a: "We don't offer investment advice, but Harrow has historically maintained strong demand due to its schools and transport. For remortgage purposes, lenders conduct their own valuations. We advise on the right time to remortgage based on your current rate and deal end date." },
    ],
  },
  {
    slug: "havering",
    name: "Havering",
    avgPrice: "£370,000",
    avgPriceNum: 370000,
    type: "borough",
    note: "East London's most affordable borough — popular with families seeking space.",
    buyerProfile: "First-time buyers, families, and those moving out of more expensive inner east London.",
    localKnowledge: "Havering borders Essex and offers some of the best value for money in Greater London. Towns like Romford, Upminster, and Hornchurch attract buyers who want a house with a garden at London prices. With Elizabeth line access from Romford, commuting to central London is direct and fast.",
    faqs: [
      { q: "What is the maximum mortgage I can get in Havering on a £45,000 salary?", a: "On £45,000, most lenders will offer around £180,000-£202,500 (4-4.5x income). With Havering's lower average prices, this can work well when combined with savings. We identify lenders who will offer the highest multiple for your income type and advise on the best deals available." },
      { q: "I'm a first-time buyer looking at Romford — what mortgage advice do you have?", a: "Romford is excellent value for first-time buyers. We advise on deposit requirements, the best rates at your LTV, whether Shared Ownership makes sense, and stamp duty costs for first-time buyers. We guide you from initial enquiry through to completion." },
      { q: "Can I get a buy to let mortgage in Havering as a first-time buyer?", a: "Most buy to let lenders require you to already own your own home, though consumer buy to let rules may apply in some cases. We advise on the options available and whether a residential purchase first might be the right strategy." },
    ],
  },
  {
    slug: "hillingdon",
    name: "Hillingdon",
    avgPrice: "£420,000",
    avgPriceNum: 420000,
    type: "borough",
    note: "West London's largest borough — home to Heathrow and Uxbridge.",
    buyerProfile: "Aviation workers, Heathrow staff, and families seeking west London affordability.",
    localKnowledge: "Hillingdon stretches from Hayes and Southall in the east to Uxbridge and West Ruislip in the west, offering varied neighbourhoods at different price points. With Elizabeth line access across the borough, London connectivity has improved. A significant proportion of buyers work in aviation or healthcare.",
    faqs: [
      { q: "I work shifts at Heathrow — will lenders consider my shift pay?", a: "Yes, shift allowances and enhancements are accepted income by most lenders, though treatment varies. We present your full income — base pay plus shift premium — to lenders who recognise variable income most favourably." },
      { q: "Can I get mortgage advice for a new-build in Hayes?", a: "New-builds in Hayes and West Drayton are popular given Elizabeth line access. We advise on new-build mortgage timelines, help you select the right rate, and ensure your AIP is in place before you reserve." },
      { q: "Is Hillingdon good for buy to let near Heathrow?", a: "Properties near Heathrow attract airport staff and short-stay renters. Yield potential varies by area and property type. We advise on buy to let mortgage criteria, rental income assessment, and the most appropriate lender for your situation." },
    ],
  },
  {
    slug: "hounslow",
    name: "Hounslow",
    avgPrice: "£480,000",
    avgPriceNum: 480000,
    type: "borough",
    note: "West London borough with great transport, cultural diversity, and improving values.",
    buyerProfile: "Professionals commuting west, aviation workers, and South Asian community buyers.",
    localKnowledge: "Hounslow has seen steady price growth driven by Heathrow proximity and District line access. Areas like Chiswick (on the eastern edge) command significant premiums. We advise buyers on the full range of neighbourhoods and which mortgage options suit different price points within the borough.",
    faqs: [
      { q: "How does self-employed income work for a mortgage in Hounslow?", a: "Lenders typically require 2 years of accounts or SA302s for self-employed applicants. Some lenders will consider 1 year if you have a strong track record in your industry. We identify which approach gives you the best result for your specific income profile." },
      { q: "What are the mortgage options for a Hounslow property with a short lease?", a: "Leases below 80 years significantly restrict mortgage options. Above 85 years, most lenders are comfortable. Below 80, you're looking at specialist lenders or negotiating a lease extension simultaneously. We advise on the process and costs involved." },
      { q: "Can I remortgage in Hounslow to raise a deposit for a second property?", a: "Yes — equity release through remortgage is a common way to raise a deposit for a second property. We assess your current equity, the impact on your monthly payments, and whether the numbers make sense for the investment you're considering." },
    ],
  },
  {
    slug: "islington",
    name: "Islington",
    avgPrice: "£750,000",
    avgPriceNum: 750000,
    type: "borough",
    note: "Prime inner north London — Angel, Highbury, and Upper Street command premium prices.",
    buyerProfile: "High-earning professionals, media workers, and political/legal professionals in central north London.",
    localKnowledge: "Islington is consistently one of London's most desirable inner boroughs. At £750,000 average, buyers need substantial income and typically require advice on maximising borrowing within a competitive market. Many buyers in Islington are also selling a property simultaneously — coordination of the chain is as important as the mortgage itself.",
    faqs: [
      { q: "How do I maximise my mortgage borrowing for an Islington purchase?", a: "Maximising borrowing in Islington involves identifying lenders with the highest income multiples for your income type, presenting any secondary income (bonus, rental, freelance) in the most favourable way, and sometimes considering specialist lenders who can offer more. We assess your full position before advising." },
      { q: "I'm a barrister/self-employed solicitor buying in Islington — how is my income assessed?", a: "Professional self-employed income, particularly for barristers and legal professionals, is treated well by some lenders who understand the earning trajectory of this profession. We identify lenders with professional mortgage products and explain exactly what documentation you'll need." },
      { q: "What advice do you give on buying in a chain in Islington's competitive market?", a: "In a competitive market, being mortgage-ready is essential. We ensure your Decision in Principle is current and your documentation is prepared in advance so that once you're in a chain, your application can proceed immediately without delays on your side." },
    ],
  },
  {
    slug: "kensington-and-chelsea",
    name: "Kensington and Chelsea",
    avgPrice: "£1,200,000",
    avgPriceNum: 1200000,
    type: "borough",
    note: "London's most expensive borough — prime and super-prime property market.",
    buyerProfile: "Ultra-high-net-worth buyers, overseas investors, and wealthy professionals in prime London.",
    localKnowledge: "Kensington and Chelsea represents the peak of the London property market. At this level, mortgage advice is genuinely bespoke — private banks, wealth managers, and specialist lenders operate alongside mainstream lenders. We advise buyers on the full range of financing options available at this price point.",
    faqs: [
      { q: "Do I even need a mortgage for a Kensington and Chelsea property?", a: "Many buyers at this level purchase cash, but using a mortgage can make financial sense — preserving liquidity, leveraging low rates against invested capital, or for tax planning purposes. We advise on the full financing picture, including when a mortgage adds value even when cash is available." },
      { q: "Which private banks offer the best mortgages for prime London properties?", a: "Private bank relationships are bespoke and depend on your overall wealth profile, not just the mortgage. As an independent adviser, we have relationships with a range of private and specialist lenders and can advise on who to approach for your specific situation." },
      { q: "What are the stamp duty costs for a £1.2m purchase in Kensington?", a: "On a £1.2m residential purchase, stamp duty is approximately £63,750 for a primary residence, rising to £99,750 if it's a second property (with 3% surcharge). These are significant costs that we factor into your overall financing plan from day one." },
    ],
  },
  {
    slug: "kingston-upon-thames",
    name: "Kingston upon Thames",
    avgPrice: "£530,000",
    avgPriceNum: 530000,
    type: "borough",
    note: "Attractive south-west London riverside town with excellent retail and schools.",
    buyerProfile: "Families upsizing from inner London, professionals, and Surrey commuter buyers.",
    localKnowledge: "Kingston upon Thames is one of south-west London's most attractive destinations, with a vibrant town centre, riverside, and strong schools. It attracts buyers moving out of higher-cost Wimbledon and Richmond. Mortgage advice here often involves helping clients understand the transition from renting to owning at this price point.",
    faqs: [
      { q: "What is the mortgage process for a first-time buyer in Kingston?", a: "We begin with an affordability assessment to determine your maximum purchase price, then advise on deposit requirements, the best mortgage deals, stamp duty costs, and all fees involved. Our goal is to make the whole process clear and manageable from start to finish." },
      { q: "Can I get mortgage advice if I'm buying in Kingston with a Help to Buy ISA?", a: "Help to Buy ISAs are still valid for eligible purchases. The government bonus (up to £3,000 per ISA holder) is paid on completion through your solicitor. We advise on how to use your ISA alongside your mortgage application." },
      { q: "What remortgage options are available for Kingston homeowners coming off a fixed rate?", a: "As your fixed rate ends, we compare your current lender's retention offer against the full market. In most cases, switching to a new lender delivers a better outcome. We handle the full remortgage process, which is typically straightforward for existing homeowners with equity." },
    ],
  },
  {
    slug: "lambeth",
    name: "Lambeth",
    avgPrice: "£560,000",
    avgPriceNum: 560000,
    type: "borough",
    note: "South London's cultural heart — Brixton, Clapham, Streatham, and the South Bank.",
    buyerProfile: "Young professionals, first-time buyers, and culturally engaged buyers in vibrant south London.",
    localKnowledge: "Lambeth spans everything from the South Bank and Waterloo to Brixton and Streatham. It's one of the most diverse boroughs in London and attracts a high proportion of first-time buyers and professionals making their first step on the property ladder. Mortgage advice in Lambeth often involves helping buyers understand how to optimise their application in a competitive market.",
    faqs: [
      { q: "I'm renting in Brixton and want to buy — where do I start?", a: "The first step is understanding your borrowing capacity. We'll assess your income, outgoings, and deposit to give you a clear maximum purchase price. From there we identify the right mortgage products and help you get your documentation ready so you're prepared to move quickly." },
      { q: "What are the mortgage options for buying near Clapham Common?", a: "Clapham is one of south London's most competitive markets. Being mortgage-ready — with a current Agreement in Principle — is essential. We ensure your mortgage is fully prepared so when you find the right property, you can act without delay." },
      { q: "Can I get mortgage advice for a leasehold flat in Lambeth?", a: "Leasehold flats are the norm in Lambeth. Key considerations are lease length (aim for 90+ years), service charges, and any building safety certificate requirements post-Grenfell. We check all these factors early to avoid issues at the point of mortgage application." },
    ],
  },
  {
    slug: "lewisham",
    name: "Lewisham",
    avgPrice: "£430,000",
    avgPriceNum: 430000,
    type: "borough",
    note: "South-east London borough with growing popularity and Elizabeth line access at Lewisham.",
    buyerProfile: "First-time buyers, young families, and buyers seeking value in south-east London.",
    localKnowledge: "Lewisham has become increasingly popular with buyers priced out of neighbouring Southwark and Greenwich. The Elizabeth line connection at Lewisham station has enhanced its appeal. Areas like Brockley, Forest Hill, and New Cross attract buyers who value connectivity with a more relaxed south London feel.",
    faqs: [
      { q: "Is Lewisham affordable for a single buyer on £50,000?", a: "On £50,000, you could borrow around £200,000-£225,000. With savings of £43,000+ for a deposit, properties in Lewisham's more affordable streets become achievable. We'll assess your full position and identify the most appropriate approach for your income level." },
      { q: "What mortgage advice do you give for converted ex-council properties in Lewisham?", a: "Former local authority flats have some lender restrictions — some lenders won't lend on ex-council properties above a certain floor or in certain block types. We identify which lenders are comfortable with the specific property and ensure valuers familiar with ex-council stock are used." },
      { q: "I'm buying with a friend in Lewisham — what's the best mortgage structure?", a: "Buying with a friend is common in London. You can own as joint tenants (equal shares) or tenants in common (unequal shares). We advise on the mortgage structure, the importance of a cohabitation agreement, and what happens to the mortgage if one of you wants to sell or buy out the other." },
    ],
  },
  {
    slug: "merton",
    name: "Merton",
    avgPrice: "£520,000",
    avgPriceNum: 520000,
    type: "borough",
    note: "South-west London borough home to Wimbledon — popular with families and sports fans.",
    buyerProfile: "Families, upsizing professionals, and buyers attracted by Wimbledon's schools and tennis heritage.",
    localKnowledge: "Merton is dominated by Wimbledon's reputation — good schools, great transport, and a strong community feel. Property ranges from flats in Wimbledon town to houses in Raynes Park and Morden. Mortgage advice here often involves helping buyers understand what they can realistically afford in different parts of the borough.",
    faqs: [
      { q: "How does affordability work for a Wimbledon property in Merton?", a: "Wimbledon's prices can exceed the borough average significantly. We model your affordability across different parts of Merton so you have realistic expectations — and identify whether neighbouring areas like Raynes Park might offer better value for your budget." },
      { q: "What mortgage options are there for Merton buyers coming from outside London?", a: "Many buyers come from outside London and may have equity in a regional property. We advise on how to structure the chain — whether to sell first or consider bridging finance — and ensure your London mortgage is in place ahead of any purchase." },
      { q: "Can I get mortgage advice on a Victorian terrace in Merton with non-standard construction?", a: "Victorian terraces in Merton are generally straightforward for lenders, but non-standard elements — timber frame extensions, alterations, or unusual construction — need careful assessment. We identify lenders comfortable with the specific property and advise on survey options." },
    ],
  },
  {
    slug: "newham",
    name: "Newham",
    avgPrice: "£400,000",
    avgPriceNum: 400000,
    type: "borough",
    note: "East London's regeneration hotspot — home to Stratford and the Olympic Park.",
    buyerProfile: "First-time buyers, investors, and buyers attracted by Crossrail and Olympic legacy regeneration.",
    localKnowledge: "Newham's transformation since the 2012 Olympics has been remarkable. Stratford is now a major hub with the Elizabeth line, and regeneration continues across West Ham and Royal Docks. Mortgage advice in Newham frequently involves new-build purchases where understanding developer timelines and mortgage offer validity is critical.",
    faqs: [
      { q: "What should I know about getting a mortgage for a new-build in Stratford?", a: "New-build mortgages have specific challenges: lenders' offers typically last 6 months but new-build completions can be delayed. We identify lenders with longer offer periods or who are willing to extend, and we keep your application live throughout the developer's build programme." },
      { q: "I want to invest in Newham for the long term — what mortgage advice do you give?", a: "Long-term investment strategy combines mortgage advice with considerations of rental yield, tenant demand, and area trajectory. We advise on the right mortgage structure — personal name versus limited company — and the most competitive buy to let rates for Newham properties." },
      { q: "Are there affordable housing schemes available in Newham?", a: "Yes — Newham has active Shared Ownership and First Homes developments. The Royal Docks and other regeneration areas often have qualifying developments. We advise on eligibility criteria and which mortgage lenders participate in each scheme." },
    ],
  },
  {
    slug: "redbridge",
    name: "Redbridge",
    avgPrice: "£450,000",
    avgPriceNum: 450000,
    type: "borough",
    note: "East London borough with Central line access and strong community feel.",
    buyerProfile: "Families, first-time buyers, and investors attracted by north-east London value.",
    localKnowledge: "Redbridge — encompassing Ilford, Woodford, and Wanstead — offers a mix of urban and suburban living with good Central line access. Ilford's Elizabeth line station has driven renewed interest. The borough has a large and diverse community and often attracts buyers seeking good schools alongside value for money.",
    faqs: [
      { q: "Is Ilford a good area for first-time buyers with the Elizabeth line?", a: "Ilford's Elizabeth line connectivity to central London in under 20 minutes makes it very attractive for first-time buyers. At around £400-450,000 for the area, it's more accessible than many inner London boroughs. We advise on the best mortgage and any relevant affordable housing schemes." },
      { q: "What mortgage options are available for large family homes in Woodford?", a: "Larger properties in Woodford can command higher prices. We assess your full household income — including any secondary income — and identify lenders offering the most favourable borrowing multiples for your situation." },
      { q: "Can I get a mortgage in Redbridge with a small business that's only been running one year?", a: "Yes, though it's more challenging. Some lenders will consider one year of accounts for self-employed applicants, particularly if you have a track record in the same industry. We identify which lenders are most flexible on self-employment history and advise accordingly." },
    ],
  },
  {
    slug: "richmond-upon-thames",
    name: "Richmond upon Thames",
    avgPrice: "£650,000",
    avgPriceNum: 650000,
    type: "borough",
    note: "South-west London's premium riverside borough — Richmond Park, Kew, and Twickenham.",
    buyerProfile: "High-earning professionals, families, and buyers prioritising green space and premium schools.",
    localKnowledge: "Richmond upon Thames consistently ranks among London's most desirable boroughs, driven by outstanding schools, Richmond Park, and riverside living in Barnes, Kew, and Richmond itself. At £650,000 average, buyers need solid incomes and careful mortgage planning. We advise on maximising borrowing within responsible limits for this premium market.",
    faqs: [
      { q: "Can I get a mortgage for a Richmond upon Thames property if I work in financial services with a large bonus?", a: "Yes. Many buyers in Richmond work in finance. Bonus income can significantly increase your borrowing power if presented correctly. We identify lenders who take the most favourable view of bonus income and advise on how to time your application." },
      { q: "What mortgage options are available for period properties in Kew or Barnes?", a: "Period properties in these areas are generally mortgageable through mainstream lenders, though unusual construction or listed buildings may require specialist lenders or specific survey types. We advise on which lender and survey approach suits the property." },
      { q: "Should I use a mortgage broker or an independent adviser for a Richmond property?", a: "An independent whole-of-market mortgage adviser has access to the full market — not just a panel of lenders. In a premium market like Richmond, this breadth of access can find products that make a meaningful difference to your monthly payments and overall cost." },
    ],
  },
  {
    slug: "southwark",
    name: "Southwark",
    avgPrice: "£580,000",
    avgPriceNum: 580000,
    type: "borough",
    note: "Inner south London — Bermondsey, Peckham, and London Bridge prime commuter territory.",
    buyerProfile: "Young professionals, first-time buyers, and investors in one of south London's most vibrant boroughs.",
    localKnowledge: "Southwark spans everything from the world-famous London Bridge and Borough Market area to the rapidly gentrifying Peckham and Dulwich Village. It's one of the most active first-time buyer and investor markets in south London. Getting mortgage advice right here means being ready to move quickly in a competitive market.",
    faqs: [
      { q: "What deposit do I need to buy a flat in Bermondsey or Peckham?", a: "At £580,000 borough average, a 10% deposit of £58,000 gives you access to competitive rates. A 5% deposit is possible but limits lender choice. We advise on the right LTV strategy based on your deposit and the specific property." },
      { q: "Is Peckham a good investment for buy to let?", a: "Peckham has seen strong rental demand and price appreciation. For buy to let, lenders will stress test the rental income to ensure it covers the mortgage. We model whether the rental yield supports a buy to let mortgage and advise on the best structure." },
      { q: "What mortgage advice is available for buying in a Southwark regeneration area?", a: "Regeneration areas carry some valuation risk — lenders sometimes down-value new developments. We identify lenders comfortable with the specific development, advise on the right survey approach, and ensure your mortgage is structured to account for any valuation differences." },
    ],
  },
  {
    slug: "sutton",
    name: "Sutton",
    avgPrice: "£410,000",
    avgPriceNum: 410000,
    type: "borough",
    note: "South London's family-friendly borough with excellent state schools.",
    buyerProfile: "Families, upsizers, and buyers seeking Ofsted-outstanding school catchments in south London.",
    localKnowledge: "Sutton is highly regarded for its state schools — Nonsuch and Wallington Grammar attract buyers from across south London. Property is more affordable than neighbouring Merton and Kingston, making it attractive for families maximising space within their budget. Mortgage advice in Sutton often involves helping buyers understand what they can get for their money in different parts of the borough.",
    faqs: [
      { q: "What mortgage do I need to buy in the catchment area of a Sutton grammar school?", a: "Catchment purchases can command premiums for certain properties. We advise on how to structure your mortgage to maximise your budget for the specific area you're targeting, including any flexibility between areas of the borough." },
      { q: "Can I use a remortgage to fund a loft conversion in Sutton?", a: "Yes — a further advance or remortgage can release equity for home improvements. We compare retention offers from your current lender with whole-of-market remortgage rates and advise on the most cost-effective way to fund the works." },
      { q: "What's the mortgage process for buying a larger house in Sutton when we have a Help to Buy loan?", a: "If you have a Help to Buy equity loan, you'll need to repay it (or staircase to higher equity) before remortgaging or selling. We advise on the process and timing, and help you understand the financial implications before you commit." },
    ],
  },
  {
    slug: "tower-hamlets",
    name: "Tower Hamlets",
    avgPrice: "£550,000",
    avgPriceNum: 550000,
    type: "borough",
    note: "East London's most dynamic borough — Canary Wharf, Bethnal Green, and Bow.",
    buyerProfile: "Canary Wharf workers, first-time buyers, and investors in east London's most diverse borough.",
    localKnowledge: "Tower Hamlets encompasses Canary Wharf — one of London's main financial centres — alongside traditional East End neighbourhoods like Bethnal Green, Bow, and Poplar. Many buyers here work in finance or the nearby financial services sector. Mortgage advice in Tower Hamlets often involves complex income structures and new-build purchases near the Canary Wharf cluster.",
    faqs: [
      { q: "I work in Canary Wharf — should I buy near work or commute from outside London?", a: "This is a financial decision as much as a lifestyle one. Buying near Canary Wharf offers convenience but at premium prices. We can model the mortgage costs for properties at different distances and price points so you can make an informed decision." },
      { q: "What are the mortgage options for high-rise flats near Canary Wharf?", a: "High-rise residential buildings near Canary Wharf require lenders comfortable with apartment blocks of this type. EWS1 certificates may apply for buildings of certain heights. We identify lenders who regularly lend on Canary Wharf-area developments without issue." },
      { q: "Can I get a buy to let mortgage for a flat in Tower Hamlets to rent to Canary Wharf workers?", a: "Tower Hamlets has strong rental demand from financial services workers. Buy to let criteria require rental income to cover the mortgage at stress rates. We calculate whether this works for the specific property and identify competitive buy to let lenders for the area." },
    ],
  },
  {
    slug: "waltham-forest",
    name: "Waltham Forest",
    avgPrice: "£420,000",
    avgPriceNum: 420000,
    type: "borough",
    note: "North-east London's up-and-coming borough — Walthamstow's E17 scene.",
    buyerProfile: "Young professionals, first-time buyers, and creatives priced out of Hackney and Islington.",
    localKnowledge: "Waltham Forest has transformed significantly, with Walthamstow becoming one of east London's most sought-after destinations. Good Victoria line access and relative affordability attract buyers who want the feel of Hackney at lower prices. Mortgage advice here often supports first-time buyers taking their initial step on the property ladder.",
    faqs: [
      { q: "Is Walthamstow a good area for a first-time buyer in 2026?", a: "Walthamstow offers strong transport links, a vibrant community, and lower prices than inner east London. At around £420,000 average, it's within reach for buyers with a good combined income and savings. We advise on all aspects of the first-time buyer mortgage process." },
      { q: "What is the first-time buyer stamp duty position for a £420,000 Walthamstow flat?", a: "First-time buyers pay no stamp duty on the first £300,000 and 5% on the portion above. On £420,000 that means stamp duty of £6,000. We include this in your overall budget planning from the first conversation." },
      { q: "Can I get a mortgage for a Walthamstow terrace that needs renovation?", a: "Most lenders will lend on properties requiring cosmetic renovation. Structural issues are more challenging and may require specialist lenders or development finance. We assess the property type and condition early to ensure you're not surprised at valuation." },
    ],
  },
  {
    slug: "wandsworth",
    name: "Wandsworth",
    avgPrice: "£620,000",
    avgPriceNum: 620000,
    type: "borough",
    note: "South-west London — Clapham, Tooting, Putney, and Battersea Power Station.",
    buyerProfile: "Professionals, upsizing families, and high earners attracted by south-west London's best areas.",
    localKnowledge: "Wandsworth covers some of London's most desirable south-west locations — Clapham South, Tooting, Putney, and the transforming Nine Elms/Battersea corridor. It's one of the most competitive markets in south London, where being mortgage-ready and having clear advice on your maximum budget is genuinely advantageous.",
    faqs: [
      { q: "How do I get mortgage advice for a Battersea Power Station flat?", a: "Battersea Power Station is a large development with multiple phases and different building types. Some lenders are familiar with this development; others are not. We identify the right lender for the specific apartment type and manage the process through their criteria." },
      { q: "I want to buy in Clapham — what's the realistic budget for a family house?", a: "Clapham family houses can reach £900k+ on desirable streets. We assess your full household income and advise on the realistic range you can achieve with your income and deposit. Sometimes the answer is a flat in Clapham or a house in neighbouring Tooting." },
      { q: "What mortgage advice do you give for a Wandsworth buyer with stock options as part of their pay?", a: "Unvested stock options are generally not considered by lenders. Vested options that have been sold and converted to cash may be treated as a bonus or savings. We advise on how to present your compensation package most effectively and which lenders are best suited to your income structure." },
    ],
  },
  {
    slug: "westminster",
    name: "Westminster",
    avgPrice: "£900,000",
    avgPriceNum: 900000,
    type: "borough",
    note: "Heart of London — Mayfair, Marylebone, Pimlico, and political London.",
    buyerProfile: "Ultra-high-net-worth individuals, international buyers, and senior professionals in prime London.",
    localKnowledge: "Westminster encompasses some of the world's most expensive real estate — Mayfair, Belgravia (which overlaps with Kensington and Chelsea), and Marylebone. At £900,000 average, buyers need bespoke financing advice that considers private banking relationships, offshore income, and complex financial structures.",
    faqs: [
      { q: "Can I get a mortgage on a Westminster property with overseas income?", a: "Yes, though fewer lenders participate. Eligibility depends on residency status, income source, currency, and deposit. Private banks and specialist international lenders are often the right route. We advise on which lenders to approach based on your specific profile." },
      { q: "What stamp duty will I pay on a £900,000 Westminster flat as a second home?", a: "On £900,000 with the second property surcharge, stamp duty would be approximately £81,750 (using standard 3% surcharge rates). This is a significant cost that we factor into financing discussions from the outset." },
      { q: "Why use an independent mortgage adviser for a Westminster property when I have a private bank?", a: "Your private bank offers only their products. As an independent adviser, we compare multiple private banks, specialist lenders, and the full mainstream market. This breadth of access often identifies a meaningfully better product, even at this price point." },
    ],
  },
  {
    slug: "surrey",
    name: "Surrey",
    avgPrice: "£560,000",
    avgPriceNum: 560000,
    type: "county",
    note: "Premier Home Counties location — Guildford, Surrey Hills, and London commuter belt.",
    buyerProfile: "London professionals relocating for space, families targeting outstanding schools, and rural lifestyle buyers.",
    localKnowledge: "Surrey offers a combination of outstanding schools, green space, and fast trains to London. Many buyers are London-based professionals making a lifestyle move. Mortgage advice for Surrey buyers often involves managing a London sale alongside a Surrey purchase, and understanding how equity from a London property works in the Home Counties context.",
    faqs: [
      { q: "I'm selling my London flat to buy a Surrey family home — what mortgage advice do I need?", a: "Coordinating a London sale with a Surrey purchase requires careful sequencing. We advise on whether to sell first or proceed in a chain, what mortgage you can access based on equity from your London sale, and how to bridge any timing gap if needed." },
      { q: "Can I get a whole-of-market mortgage for a Surrey rural property?", a: "Rural properties, particularly those with land or non-standard construction, may restrict lender choice. We identify lenders comfortable with the specific property type and location, and advise on survey requirements for agricultural or unusual properties." },
      { q: "What is the stamp duty position for buying in Surrey as a second property?", a: "A second property incurs a 3% surcharge on all standard stamp duty bands. We calculate the exact cost for your purchase price and factor it into your overall financing plan." },
    ],
  },
  {
    slug: "essex",
    name: "Essex",
    avgPrice: "£340,000",
    avgPriceNum: 340000,
    type: "county",
    note: "Affordable Home Counties option — Chelmsford, Brentwood, and Elizabeth line towns.",
    buyerProfile: "First-time buyers, London commuters, and families seeking maximum space for budget.",
    localKnowledge: "Essex offers some of the most accessible property prices within commuting distance of London. Elizabeth line towns like Brentwood and Shenfield, and Crossrail-served Chelmsford via GW mainline, attract buyers who want to maximise space without sacrificing London access. Mortgage advice here often involves first-time buyers taking advantage of lower prices.",
    faqs: [
      { q: "Can I commute from Essex to central London on a first-time buyer budget?", a: "Yes — towns like Chelmsford (35 minutes to Liverpool Street), Brentwood, and Basildon offer good value. We advise on the maximum mortgage available on your income and help identify the best balance between property size, location, and commute cost." },
      { q: "Are there first-time buyer schemes available in Essex?", a: "Shared Ownership and First Homes are active in Essex, particularly on new-build developments in growth areas. We advise on which schemes you're eligible for and which lenders participate." },
      { q: "What mortgage advice do you give for buying a period property in a village in Essex?", a: "Period properties in Essex villages are generally mortgageable, though unusual construction, thatched roofs, or timber frame may restrict lender choice. We identify lenders comfortable with the property type and advise on the appropriate survey level." },
    ],
  },
  {
    slug: "kent",
    name: "Kent",
    avgPrice: "£320,000",
    avgPriceNum: 320000,
    type: "county",
    note: "The Garden of England — affordable coastal and rural options within reach of London.",
    buyerProfile: "Remote workers, families relocating from London, and buyers seeking coastal living.",
    localKnowledge: "Kent offers some of the most affordable property within reasonable reach of London, with fast trains from Ashford and Ebbsfleet to St Pancras. Post-pandemic remote working has increased Kent's appeal significantly. Mortgage advice for Kent buyers often involves those making a significant lifestyle move from London, using substantial equity to reduce their mortgage.",
    faqs: [
      { q: "Can I use equity from a London property to buy mortgage-free or near mortgage-free in Kent?", a: "With London equity and a lower Kent purchase price, many buyers can significantly reduce or eliminate their mortgage. We advise on the best use of equity — whether to pay down the mortgage or retain capital — based on your overall financial position." },
      { q: "What mortgage options are available for a coastal property in Kent?", a: "Coastal properties can have lender restrictions, particularly above sea cliffs or in flood risk areas. We identify lenders comfortable with coastal locations and advise on the appropriate survey type — a full structural survey is usually recommended." },
      { q: "Are there fast trains from Kent to London for commuters?", a: "Yes — Ebbsfleet to St Pancras takes around 17 minutes, and Ashford International is under 40 minutes. We help buyers understand the full cost of ownership including commuting costs when assessing affordability for Kent properties." },
    ],
  },
  {
    slug: "hertfordshire",
    name: "Hertfordshire",
    avgPrice: "£420,000",
    avgPriceNum: 420000,
    type: "county",
    note: "North of London — St Albans, Watford, and Welwyn Garden City commuter belt.",
    buyerProfile: "London professionals, families with children, and buyers moving north up the M1/M25 corridor.",
    localKnowledge: "Hertfordshire is a popular destination for London professionals moving for space and schools. St Albans, Harpenden, and Wheathampstead are particularly desirable. Thameslink provides fast links to London Bridge and St Pancras. Mortgage advice in Hertfordshire often supports buyers making significant upsizing moves using London equity.",
    faqs: [
      { q: "What mortgage advice do you give for buying in St Albans versus Watford?", a: "St Albans commands significant premiums over Watford due to its schools, town centre, and demand. We help buyers understand what they can achieve in each area and model the financial difference between the two — so the decision is informed by clear numbers." },
      { q: "Can I use rental income from a London property to support a Hertfordshire mortgage?", a: "Rental income from an existing property can be considered as income by some lenders. We identify which lenders take the most favourable view of rental income alongside employment income and advise on the most effective approach." },
      { q: "What are the mortgage options for buying land to build in Hertfordshire?", a: "Self-build mortgages work differently from standard residential mortgages — funds are released in stages as construction progresses. We advise on self-build mortgage options, which are available from a more limited range of lenders but are achievable with the right advice." },
    ],
  },
  {
    slug: "berkshire",
    name: "Berkshire",
    avgPrice: "£400,000",
    avgPriceNum: 400000,
    type: "county",
    note: "West of London — Reading, Windsor, and Maidenhead on the Elizabeth line.",
    buyerProfile: "Technology workers, Thames Valley professionals, and London commuters seeking west London value.",
    localKnowledge: "Berkshire sits on the Elizabeth line corridor, with Reading being a major employment hub for technology and financial services. Windsor and Maidenhead are attractive for buyers wanting premium towns at lower-than-London prices. Mortgage advice in Berkshire often supports buyers relocating from London or moving within the Thames Valley for work.",
    faqs: [
      { q: "Is Reading a good location for a buy to let investment near the tech sector?", a: "Reading has strong rental demand from Oracle, Microsoft, and other tech employers. Yields can be solid relative to purchase prices. We advise on buy to let mortgage criteria, rental income assessment, and the best structure for your investment." },
      { q: "Can I get mortgage advice for buying near Windsor as a buyer relocating from central London?", a: "Windsor properties command a premium within Berkshire. We advise on maximising your borrowing from a London equity position and identify lenders who are competitive in the £400,000-£600,000 range for this area." },
      { q: "What mortgage advice do you give for new-build properties in Maidenhead on the Elizabeth line?", a: "New-builds in Maidenhead benefit from excellent Elizabeth line connectivity. We advise on new-build mortgage timelines, the right rate to reserve (factoring in potential completion dates), and which lenders are comfortable with the specific development." },
    ],
  },
];

export function getAreaBySlug(slug: string): AreaData | undefined {
  return areas.find((a) => a.slug === slug);
}

export function getAllSlugs(): string[] {
  return areas.map((a) => a.slug);
}
